app {
  name = "EcommerceAnalytics"
  data {
    input {
      transactions = "data/transactions.csv"
      users = "data/users.json"
      products = "data/products.parquet"
      merchants = "data/merchants.csv"
    }
  }
}