app {
  name = "EcommerceAnalytics"
  data {
    input {
      # Chemins relatifs vers la landing zone
      transactions = "src/main/resources/data/transactions.csv"
      users = "src/main/resources/data/users.json"
      products = "src/main/resources/data/products.parquet"
      merchants = "src/main/resources/data/merchants.csv"
    }
    output {
      # Répertoire où seront sauvegardés les résultats finaux
      path = "output/analytics_results"
    }
  }
}